### PR TITLE
Fix running on linux

### LINKED ISSUE #6: Does not work on linux
The issue is due to the fact that `xcrun` is called which does not exist on linux.
https://github.com/shibapm/PackageConfig/blob/89d196830ebc6b3d7fdead6391b5ae9230883b87/Sources/PackageConfig/Package.swift#L10

What is the reason for using `xcrun` vs just doing something like `command -v swiftc` to get the path to the `swiftc` binary?

### PR DESCRIPTION
**Pull request by cszatma**
* Use `command -v` to get `swiftc` path instead of `xcrun` since `xcrun` isn't available on linux.
* On linux there is a `llbuild` directory at `lib/swift/pm` so filter it out when resolving the `PackageDescription` library path.
* Try using swift tools version specified in `Package.swift`  when resolving library path, otherwise default to latest available.

Closes #6

### CODE REVIEW

File: Sources/PackageConfig/Package.swift [hunk 1]
```diff
@@ -100,12 +100,35 @@ enum Package {
...
+
+        let swiftToolsVersion = getSwiftToolsVersion()
+        let spmDir = versions.contains(swiftToolsVersion) ? swiftToolsVersion : versions.sorted().last!
+		let libraryPathSPM = swiftPMDir + "/" + spmDir
 
 		debugLog("Using SPM version: \(libraryPathSPM)")
 		return ["-L", libraryPathSPM, "-I", libraryPathSPM, "-lPackageDescription"]
 	}
+    
+    static private func getSwiftToolsVersion() -> String {
```
Comment (f-meloni) [inline Sources/PackageConfig/Package.swift]: I think you could use `String?`, IMO `nil` is more clear than `""` for when you don't have a version

File: Sources/PackageConfig/Package.swift [hunk 2]
```diff
@@ -100,12 +100,35 @@ enum Package {
...
+        guard let data = FileManager.default.contents(atPath: "Package.swift") else {
+            return ""
+        }
+        
+        let contents = String(data: data, encoding: .utf8)
+        guard let version = contents?.components(separatedBy: "\n").first?.components(separatedBy: ":").last else {
```
Comment (f-meloni) [inline Sources/PackageConfig/Package.swift]: I think a regex here could make it more robust, what is your opinion?

File: Sources/PackageConfig/Package.swift [hunk 3]
```diff
@@ -100,12 +100,35 @@ enum Package {
...
+        let swiftToolsVersion = getSwiftToolsVersion()
+        let spmDir = versions.contains(swiftToolsVersion) ? swiftToolsVersion : versions.sorted().last!
+		let libraryPathSPM = swiftPMDir + "/" + spmDir
 
 		debugLog("Using SPM version: \(libraryPathSPM)")
 		return ["-L", libraryPathSPM, "-I", libraryPathSPM, "-lPackageDescription"]
 	}
+    
+    static private func getSwiftToolsVersion() -> String {
+        guard let data = FileManager.default.contents(atPath: "Package.swift") else {
```
Comment (f-meloni) [inline Sources/PackageConfig/Package.swift]: https://developer.apple.com/documentation/swift/string/3126738-init should allow you you to remove `let contents = String(data: data, encoding: .utf8)` and make it all in one line

File: Sources/PackageConfig/Package.swift [hunk 4]
```diff
@@ -100,12 +100,35 @@ enum Package {
 		let fileManager = FileManager.default
 
 		let swiftPMDir = swiftPath.replacingOccurrences(of: "bin/swiftc", with: "lib/swift/pm")
-		let versions = try! fileManager.contentsOfDirectory(atPath: swiftPMDir)
-		#warning("TODO: handle //swift-tools-version:4.2 declarations")
-		let latestSPM = versions.sorted().last!
-		let libraryPathSPM = swiftPMDir + "/" + latestSPM
+		let versions = try! fileManager.contentsOfDirectory(atPath: swiftPMDir).filter { $0 != "llbuild" }
+
+        let swiftToolsVersion = getSwiftToolsVersion()
```
Comment (f-meloni) [inline Sources/PackageConfig/Package.swift]: I think this code probably needs to be re indented

Comment (f-meloni) [reply Sources/PackageConfig/Package.swift]: Probably we should use https://github.com/shibapm/Komondor to be sure everything is formatted correctly 🤔

File: Sources/PackageConfig/Package.swift [hunk 5]
```diff
@@ -1,111 +1,146 @@
...
+        return ["-L", libraryPathSPM, "-I", libraryPathSPM, "-lPackageDescription"]
+    }
+    
+    static private func getSwiftToolsVersion() -> String? {
+        guard let contents = try? String(contentsOfFile: "Package.swift") else {
+            return nil
+        }
+
+        let range = NSRange(location: 0, length: contents.count)
+        guard let regex = try? NSRegularExpression(pattern: #"^// swift-tools-version:(?:(\d)\.(\d)(?:\.\d)?)$"#) else {
```
Comment (f-meloni) [inline Sources/PackageConfig/Package.swift]: What about chaining the guards?
```swift
guard let regex = try? NSRegularExpression(pattern: #"^// swift-tools-version:(?:(\d)\.(\d)(?:\.\d)?)$"#),
          let match = regex.firstMatch(in: contents, options: [], range: range)
          let majorRange = Range(match.range(at: 1), in: contents), let major = Int(contents[majorRange]),
          let minorRange = Range(match.range(at: 2), in: contents), let minor = Int(contents[minorRange]) else {
            return nil
        }
```

**Comment by f-meloni** [comment]
Thank you! :)
